# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 09:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='COMMENTS',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='FLAG_DELETE',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brand',
            name='LAST_MODIFIED',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 18, 9, 25, 4, 260262, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
