# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 07:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0002_auto_20160218_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='COMMENTS',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='FLAG_DELETE',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='LAST_MODIFIED',
        ),
    ]
