# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0003_auto_20160219_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gtin_img',
            fields=[
                ('GTIN_CD', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('GTIN_IMG', models.BinaryField()),
            ],
        ),
    ]
