# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0004_gtin_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand_img',
            fields=[
                ('BSIN', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('BSIN_IMG', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Owner_img',
            fields=[
                ('OWNER_CD', models.IntegerField(primary_key=True, serialize=False)),
                ('OWNER_IMG', models.BinaryField()),
            ],
        ),
    ]
