# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 01:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0005_brand_img_owner_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Owner_img',
            new_name='Brand_owner_img',
        ),
    ]
