# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0006_auto_20160222_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search_api',
            fields=[
                ('GTIN_CD', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('SEARCH_NB', models.IntegerField(default=1)),
            ],
        ),
    ]
